name: Continuous Integration
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@master
    - name: Pull dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build Puiroject
      run: dotnet build dot-files

